api_url: "http://localhost:3000/rights-explorer/generateSqlWithSummary"
session_id: "abc120"
user_intent: "what rights do we have for the property 191754.002"
questions:
  - "How many deals are associated with property 191754.002?"
  - "Does property 191754.002 include Pay TV as a primary right?"
thresholds:
  good: 0.85
  moderate: 0.65