api_url: "http://your-api-url"
user_intent: "what rights do we have for the property 191754.002"
sql_text: "WITH top_title AS (
  SELECT pt.title_id, pt.title_source, pt.title_source_id, pt.program_type, pt.program_name,
         COUNT(*) OVER () AS total_title_count
  FROM rights_explorer_schema.program_title pt
  WHERE pt.title_source_id = '191754.002'
  ORDER BY pt.title_source, pt.title_source_id DESC
  LIMIT 1
  ) 
    SELECT tt.title_id, tt.title_source, tt.title_source_id, tt.program_type, tt.program_name,
          mr.media_rights_id, mr.rights_source, mr.rights_type, mr.deal_id, mr.hive_deal_id,
          mr.deal_name, mr.deal_type, mr.term_from, mr.term_to, mr.estimated_term_from,
          mr.estimated_term_to, mr.exclusivity, mr.holdback, mr.notes, mr.restricted_notes,
          mr.end_user_rights, mr.media_types, mr.countries, mr.brands,
          tt.total_title_count,
          'ListTitleRights' AS result_type
    FROM top_title tt
    JOIN rights_explorer_schema.program_title_media_rights ptmr ON tt.title_id = ptmr.title_id
    JOIN rights_explorer_schema.media_rights mr ON ptmr.media_rights_id = mr.media_rights_id"
sql_result:
  - title_id: "191754.002"
    title_source: "HIVE"
    title_source_id: "191754.002"
    program_type: "Episode"
    program_name: "Typhoon Hagibis"
    media_rights_id: 5632
    media_rights_source: "Foundry RightsLogic"
    media_rights_type: "Exhibition & Distribution"
    deal_id: 5489144
    deal_source_id: 312811
    deal_name: "Deadliest Catch (Season 16)"
    deal_type: "Commission"
    license_start: "2019-09-02"
    license_end: "9999-12-31"
    exclusivity: false
    temporary_download: false
    notes: null
    primary_rights:
      Pay TV:
        Simulcast: false
        Start Over: false
        Catch-Up: false
        Temporary Download: false
        Allowed Languages: ["All Languages"]
      Free TV:
        Simulcast: false
        Start Over: false
        Catch-Up: false
        Temporary Download: false
        Allowed Languages: ["All Languages"]
      PPV:
        Simulcast: false
        Start Over: false
        Catch-Up: false
        Temporary Download: false
        Allowed Languages: ["All Languages"]
      FAST:
        Simulcast: true
        Start Over: true
        Catch-Up: false
        Temporary Download: false
        Allowed Languages: ["All Languages"]
      TVOD:
        Simulcast: false
        Start Over: false
        Catch-Up: false
        Temporary Download: false
        Allowed Languages: ["All Languages"]
      STB VOD:
        Simulcast: false
        Start Over: false
        Catch-Up: true
        Temporary Download: false
        Allowed Languages: ["All Languages"]
      SVOD:
        Simulcast: false
        Start Over: false
        Catch-Up: false
        Temporary Download: true
        Allowed Languages: ["All Languages"]
      Download to Own:
        Simulcast: false
        Start Over: false
        Catch-Up: false
        Temporary Download: false
        Allowed Languages: ["All Languages"]
    territories: ["World Wide"]
    brands:
      - "Cooking Channel"
      - "Fatafeat"
      - "Focus"
      - "Travel & Living"
      - "HBO Max"
      - "Good Food"
      - "Discovery Turbo"
      - "Eden"
      - "MAX"
      - "TLC"
      - "Kanal 11 Sweden"
      - "Home & Health"
      - "HGTV"
      - "Asian Food Network"
      - "Discovery Kids"
      - "Rush"
      - "Metro"
      - "Great American Country"
      - "Real Time"
      - "CNN"
      - "Investigation Discovery"
      - "TV Norge"
      - "VOX"
      - "Frisbee"
      - "Kutonen"
      - "6eren"
      - "Three"
      - "Animal Planet"
      - "Discovery en Espanol"
      - "Asharq"
      - "TVN"
      - "American Heroes Channel"
      - "Dplay"
      - "The Living Channel"
      - "Other/Unknown"
      - "NOVE"
      - "Food Network"
      - "GolfTV"
      - "Discovery History"
      - "Food.com"
      - "LIV"
      - "K5 Denmark"
      - "Canal"
      - "Digital Media India - Daily Hunt"
      - "DIY Network"
      - "Shed"
      - "Discovery Channel"
      - "Quest"
      - "FEM"
      - "Kanal 9 Sweden"
      - "TNT Novelas"
      - "Discovery+"
      - "Military Channel"
      - "Bravo"
      - "OWN"
      - "Discovery HD World"
      - "Non-DCI"
      - "Genius Kitchen"
      - "Kanal 4 Denmark"
      - "Magnolia Network"
      - "People & Arts"
      - "TV5 Finland"
      - "DMAX"
      - "Discovery Family"
      - "Home"
      - "K2"
      - "Fine Living"
      - "Travel"
      - "3Net"
      - "Discovery Health"
      - "WB TV"
      - "HBO"
      - "K9 Denmark"
      - "Discovery Civilisation"
      - "HD Theater"
      - "Really"
      - "MotorTrend"
      - "TCM"
      - "GXT"
      - "Science Channel"
      - "Kanal 5 Sweden"
      - "BBC America"
      - "The Hub"
      - "Giallo"
      - "Discovery Life"
      - "Quest Red"
      - "Frii"
    total_title_count: 1
    result_type: "ListTitleRights"
num_questions: 5
generated_summary: |
  Search Summary:
  - Total matching title count: 1
  - Title selected: "Typhoon Hagibis" (Episode), ID: 99999, Source: HIVE
  - Incorporated Deal: "Deadliest Catch (Season 16)" (Commission), ID: 5489144, Source: Foundry RightsLogic

  Rights Summary:
  1. Term window: 2 Sep, 2019 to 31 Dec, 9999
     - Primary rights:
       - Pay TV: Yes
       - Free TV: Yes
       - PPV: Yes
       - FAST: Yes
       - TVOD: Yes
       - STB VOD: Yes
       - SVOD: Yes
       - Download to Own: Yes
     - Ancillary rights:
       - Catch-Up: Yes (for Pay TV, Free TV, FAST, PPV)
       - Start Over: Yes (for Pay TV, Free TV, FAST)
       - Simulcast: Yes (for Pay TV, Free TV)
       - Temporary Download: Yes (for STB VOD, TVOD, SVOD)
     - Territories: World Wide
     - Brands: Cooking Channel, Fatafeat, Focus, Travel & Living, HBO Max, Good Food, Discovery Turbo, Eden, MAX, TLC ...etc
     - Languages: All Languages
     - Notes: None
     - Exclusivity: None

  Terms Summary:
  - Overall term: 2 Sep, 2019 to 31 Dec, 9999
  - No overlaps or gaps in term windows.
ground_truth_summary: |
  Search Summary:
  - Total matching title count: 1
  - Title selected: "Typhoon Hagibis" (Episode), ID: 191754.002, Source: HIVE
  - Incorporated Deal: "Deadliest Catch (Season 16)" (Commission), ID: 5489144, Source: Foundry RightsLogic

  Rights Summary:
  1. Term window: 2 Sep, 2019 to 31 Dec, 9999
     - Primary rights:
       - Pay TV: Yes
       - Free TV: Yes
       - PPV: Yes
       - FAST: Yes
       - TVOD: Yes
       - STB VOD: Yes
       - SVOD: Yes
       - Download to Own: Yes
     - Ancillary rights:
       - Catch-Up: Yes (for Pay TV, Free TV, FAST, PPV)
       - Start Over: Yes (for Pay TV, Free TV, FAST)
       - Simulcast: Yes (for Pay TV, Free TV)
       - Temporary Download: Yes (for STB VOD, TVOD, SVOD)
     - Territories: World Wide
     - Brands: Cooking Channel, Fatafeat, Focus, Travel & Living, HBO Max, Good Food, Discovery Turbo, Eden, MAX, TLC ...etc
     - Languages: All Languages
     - Notes: None
     - Exclusivity: None

  Terms Summary:
  - Overall term: 2 Sep, 2019 to 31 Dec, 9999
  - No overlaps or gaps in term windows.
questions:
  - "What rights do we have for the property 191754.002?"
  - "What is the license start date?"
  - "What is the license end date?"
  - "Which brands are covered?"
  - "Is there exclusivity?"
thresholds:
  good: 0.85
  moderate: 0.65